### ISSUE TITLE
Small Issue Spelling Error

### ISSUE THREAD

**Issue by marcodc** [phpipam/php-snmptraps#13]
Hi,

cool tool, found a small spelling error.
the word "Maintenance" is spelled wrong in the menu and description.
correct spelling would be Maintenance

This Sentence has also some errors inside: Maintenance / arriving would be correct.

Here you can set **maintaneance** periods for specific hosts. During **maintaneance** period you will not be receiving notifications for this host, but notifications will still be **arraving** to database. 

here an example of the same sentence slightly modified for better understanding:
Here you can set maintenance periods for specific hosts. Notifications will be disabled for the duration of Maintenance period for such hosts. Notifications will still be received and written to the database.

Another Small Grammar error is under **live** menu
Messages will be updated each 15 seconds 
should be:
Messages will be updated **every** 15 seconds

Under Hosts: (i get this error)
Warning: Invalid argument supplied for foreach() in /var/www/html/snmptraps/app/host/index.php on line 74

Ignored Messages:

Grammar Fixes:
Below messages will not be placed to database, and notification message for below definitions will not be sent. If only OID is set, than trap containing this OID will not be processes. If hostname is set it will match hostname also, same goes for messages for better fine-tuning. 

here another option:
Messages listed here will not be written to the database and Notifications will not be sent. 
If either only the OID, hostname or the message is set, then traps containing this OID, hostname or message will not be processed. This allows for more granular control and better fine tuning.

i will check and if i find more spelling errors i will open a ticket.
thanks for a great tool

**Comment by phpipam** [comment]
Thanks for report, closing ticket :)
