### ISSUE TITLE
Unable to get any traps recognised

### ISSUE THREAD

**Issue by jasonyates** [phpipam/php-snmptraps#14]
I have a bunch of Cisco devices set to trap to the system however everything is coming in as Unknown.

For example, when I exit conf t, a trap gets generated and it looks like this whereas I would have expected it to be picked up by the CISCO-CONFIG-MAN-MIB

IP address	172.21.128.1
Date	24/04 16:34:52
Message	enterprises.9.0.1
OID	SNMPv2-SMI::enterprises.9.0.1
Severity	unknown

enterprises.9.2.9.3.1.1.3 => 6
enterprises.9.2.6.1.1.5.172.21.128.1.22.10.184.80.214 => 1885
enterprises.9.2.6.1.1.1.172.21.128.1.22.10.184.80.214 => 2834
enterprises.9.2.6.1.1.2.172.21.128.1.22.10.184.80.214 => 138252
enterprises.9.2.9.2.1.18 => "username"

**Comment by phpipam** [comment]
Hi, as trap arrives to system it is first parsed by snmptrapd, using MIB files in your system to decode OIDs. Usually MIB files are to be stored in `/usr/share/snmp/mibs`.

You can test this by executing snmptranslate, for your example:
```
server ~ # snmptranslate SNMPv2-SMI::enterprises.9.0.1 -On
.1.3.6.1.4.1.9.0.1
server ~ # snmptranslate SNMPv2-SMI::enterprises.9.0.1    
CISCOTRAP-MIB::tcpConnectionClose

server ~ # snmptranslate SNMPv2-SMI::enterprises.9.2.6.1.1.2.172.21.128.1.22.10.184.80.214
OLD-CISCO-TCP-MIB::loctcpConnOutBytes.172.21.128.1.22.10.184.80.214
```

If you need I can share MIBs I use. 

br

**Comment by ktoczyski** [comment]
Hi,

I have the same problem. In logs I see:

```
hostname => XXXXX
ip => 172.31.14.1
uptime => 427:2:39:17.62
oid => SNMPv2-SMI::enterprises.9.9.43.2.0.1
content => array:
	enterprises.9.9.43.1.1.6.1.3 => 1
	enterprises.9.9.43.1.1.6.1.4 => 3
	enterprises.9.9.43.1.1.6.1.5 => 2
severity => unknown
msg => enterprises.9.9.43.2.0.1
```

But when I use snmptranslete all is ok.

```
root@web01:/usr/local/share/snmp/mibs# snmptranslate SNMPv2-SMI::enterprises.9.9.43.2.0.1
CISCO-CONFIG-MAN-MIB::ciscoConfigManEvent
root@web01:/usr/local/share/snmp/mibs# snmptranslate SNMPv2-SMI::enterprises.9.9.43.1.1.6.1.3
CISCO-CONFIG-MAN-MIB::ccmHistoryEventCommandSource
root@web01:/usr/local/share/snmp/mibs# snmptranslate SNMPv2-SMI::enterprises.9.9.43.1.1.6.1.4
CISCO-CONFIG-MAN-MIB::ccmHistoryEventConfigSource
root@web01:/usr/local/share/snmp/mibs# snmptranslate SNMPv2-SMI::enterprises.9.9.43.1.1.6.1.5
CISCO-CONFIG-MAN-MIB::ccmHistoryEventConfigDestination
```

What is wrong?

Next thing.

Could you tell me how is create messages in your system? I don't understand it.
Is it possible create own message? I'm traying create severity with my message but doesn't work.

```
ip => 172.31.14.1
uptime => 427:2:34:06.07
oid => IF-MIB::linkUp
content => array:
	ifIndex => 150
	ifDescr => Loopback1
	ifType => softwareLoopback
severity => warning
msg => linkUp (Loopback1)
```

**Comment by phpipam** [comment]
Did you restart snmptrapd after adding mibs ? Reopen of it is still an issue.
