### ISSUE TITLE
Traps Unrecognized

### ISSUE THREAD

**Issue by ds2600** [phpipam/php-snmptraps#15]
OID comes in as:
`SNMPv2-SMI::enterprises.16668.1.6.13`

Should be recognized by UCRYPT-Q2Q-MIB. 

Cannot save 'Messages' associated with the trap. 

May also be beneficial to be able to manually modify what an OID is displayed as instead of individual traps.

**Comment by phpipam** [comment]
Hi, traps are processed by snmptrapd of snmp, has nothing to do with php-snmptraps.

You can check if they are processed by snmptranslate:
```
[root@server #] snmptranslate SNMPv2-SMI::enterprises.16668.1.6.13
SNMPv2-SMI::enterprises.16668.1.6.13
[root@server #] snmptranslate .1.3.6.1.2.1.14.16.2
OSPF-TRAP-MIB::ospfTraps
```

br
