### ISSUE TITLE
Password for Admin user is wrong

### ISSUE THREAD

**Issue by Mosibi** [phpipam/php-snmptraps#3]
After install php-snmptraps, i could not login with Admin/snmptraps. The following change in SCHEMA.sql fixed it for me

```
--- SCHEMA.sql.orig 2016-09-09 10:08:02.494510419 +0200
+++ SCHEMA.sql  2016-09-08 15:56:52.455407909 +0200
@@ -151,7 +151,7 @@

 INSERT INTO `users` (`id`, `username`, `real_name`, `auth_method`, `password`, `role`, `email`, `tel`, `notification_types`, `notification_severities`, `quiet_time_start`, `quiet_time_stop`, `last_login`, `last_activity`)
 VALUES
-   (1,'Admin','Admin user',X'6C6F63616C',X'243624726F756E64733D333030302447546749466E35497350655955325433246D5071374D5335692F4850337A6735663643426643766C4F682F645532304E6B6A33356A79556C44774B4D33776A6A39672F746456686343767A392F536231376965474E4C5A69587937525433683753536A44573630','administrator','ni@sploh.si',X'',X'6D61696C',X'656D657267656E63793B616C6572743B637269746963616C3B756E6B6E6F776E','00:00:00','00:00:00',NULL,NULL);
+   (1,'Admin','Admin user',X'6C6F63616C',X'243624726F756E64733D333030302447546749466E354973506559553254332448775446756E736F566864424930684C3250507871546641444E576F76716358547130624F4A4C58705330426865714A58692E4830592E7A4532363454304A444E2F50426E46597067677044504F6A4F63434B2E7731','administrator','ni@sploh.si',X'',X'6D61696C',X'656D657267656E63793B616C6572743B637269746963616C3B756E6B6E6F776E','00:00:00','00:00:00',NULL,NULL);

 /*!40000 ALTER TABLE `users` ENABLE KEYS */;
 UNLOCK TABLES;
```

**Comment by pizu** [comment]
Cheers :)

**Comment by GuyFoetz** [comment]
in addition the field hostnames in the DB has no default value, so it has to be set in the query

`--- SCHEMA.sql  2016-11-17 09:53:57.693008960 +0100
+++ SCHEMA.sql.new      2016-11-17 09:52:41.436522309 +0100
@@ -150,9 +150,9 @@
 LOCK TABLES `users` WRITE;
 /*!40000 ALTER TABLE `users` DISABLE KEYS */;
 
-INSERT INTO `users` (`id`, `username`, `real_name`, `auth_method`, `password`, `role`, `email`, `tel`, `notification_types`, `notification_severities`, `quiet_time_start`, `quiet_time_stop`, `last_login`, `last_activity`)
+INSERT INTO `users` (`id`, `username`, `real_name`, `auth_method`, `password`, `role`, `email`, `tel`, `notification_types`, `notification_severities`, `quiet_time_start`, `quiet_time_stop`, `last_login`, `last_activity`, `hostnames`)
 VALUES
-       (1,'Admin','Admin user',X'6C6F63616C',X'243624726F756E64733D333030302447546749466E35497350655955325433246D5071374D5335692F4850337A6735663643426643766C4F682F645532304E6B6A33356A79556C44774B4D33776A6A39672F746456686343767A392F536231376965474E4C5A69587937525433683753536A44573630','administrator','ni@sploh.si',X'',X'6D61696C',X'656D657267656E63793B616C6572743B637269746963616C3B756E6B6E6F776E','00:00:00','00:00:00',NULL,NULL);
+(1,'Admin','Admin user',X'6C6F63616C',X'243624726F756E64733D333030302447546749466E354973506559553254332448775446756E736F566864424930684C3250507871546641444E576F76716358547130624F4A4C58705330426865714A58692E4830592E7A4532363454304A444E2F50426E46597067677044504F6A4F63434B2E7731','administrator','ni@sploh.si',X'',X'6D61696C',X'656D657267656E63793B616C6572743B637269746963616C3B756E6B6E6F776E','00:00:00','00:00:00',NULL,NULL,'');
 
 /*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;`

**Comment by GuyFoetz** [comment]
in addition the field hostnames in the DB has no default value, so it has to be set in the query

```
--- SCHEMA.sql  2016-11-17 09:53:57.693008960 +0100
+++ SCHEMA.sql.new      2016-11-17 09:57:36.070401512 +0100
@@ -150,9 +150,9 @@
 LOCK TABLES `users` WRITE;
 /*!40000 ALTER TABLE `users` DISABLE KEYS */;

-INSERT INTO `users` (`id`, `username`, `real_name`, `auth_method`, `password`, `role`, `email`, `tel`, `notification_types`, `notification_severities`, `quiet_time_start`, `quiet_time_stop`, `last_login`, `last_activity`)
+INSERT INTO `users` (`id`, `username`, `real_name`, `auth_method`, `password`, `role`, `email`, `tel`, `notification_types`, `notification_severities`, `quiet_time_start`, `quiet_time_stop`, `last_login`, `last_activity`, `hostnames`)
 VALUES
-       (1,'Admin','Admin user',X'6C6F63616C',X'243624726F756E64733D333030302447546749466E35497350655955325433246D5071374D5335692F4850337A6735663643426643766C4F682F645532304E6B6A33356A79556C44774B4D33776A6A39672F746456686343767A392F536231376965474E4C5A69587937525433683753536A44573630','administrator','ni@sploh.si',X'',X'6D61696C',X'656D657267656E63793B616C6572743B637269746963616C3B756E6B6E6F776E','00:00:00','00:00:00',NULL,NULL);
+  (1,'Admin','Admin user',X'6C6F63616C',X'243624726F756E64733D333030302447546749466E354973506559553254332448775446756E736F566864424930684C3250507871546641444E576F76716358547130624F4A4C58705330426865714A58692E4830592E7A4532363454304A444E2F50426E46597067677044504F6A4F63434B2E7731','administrator','ni@sploh.si',X'',X'6D61696C',X'656D657267656E63793B616C6572743B637269746963616C3B756E6B6E6F776E','00:00:00','00:00:00',NULL,NULL,'');

 /*!40000 ALTER TABLE `users` ENABLE KEYS */;
UNLOCK TABLES;
```

**Comment by phpipam** [comment]
Merged.

**Comment by simon-jack** [comment]
Is this still an issue, I've downloaded the code today and cannot login with the Admin/snmptraps user
