### ISSUE TITLE
php-snmptraps CAN NOT work with nginx?

### ISSUE THREAD

**Issue by ggmo** [phpipam/php-snmptraps#31]
Thank you very much for creating Php-snmptraps. During the installation process, I found that I can't work with nginx. Can you take sometime to write related documents? Hoping for you reply, thank you!

**Comment by phpipam** [comment]
Hi, yes, I will update it when I have a chance.

Something like this should work...

```
  location / {
        try_files $uri $uri/ =404;
        index index.php;

        rewrite ^/(.*)/(.*)/(.*)/? /index.php?app=$1&page=$2&id1=$3 last;
        rewrite ^/(.*)/(.*)/(.*)/? /index.php?app=$1&page=$2 last;
        rewrite ^/(.*)/(.*)/(.*)/? /index.php?app=$1 last;
    }
```

**Comment by ggmo** [comment]
EXCELENT as always, is there a plan for automatic network configuration management tools?
like ssh netconf api
