### ISSUE TITLE
error in host tab

### ISSUE THREAD

**Issue by pizu** [phpipam/php-snmptraps#5]
Select host

Warning: Invalid argument supplied for foreach() in /var/www/html/php-snmptraps/app/host/index.php on line 74

Line 74...

```
foreach ($unique_hosts as $h) {
```

**Comment by pizu** [comment]
solved, had the traphandler path wrong.

**Comment by AlbertEinsteinGlitchPoint** [comment]
i  have the exact same error, can you please let me know about the traphandler?

i have changed in /etc/snmp/snmptrapd.conf  

the location to the location of our folder directory, all pages opening .. including the hosts.. but it throws this foreach error on line 77..

**Comment by phpipam** [comment]
Hi, this is only a warning, meaning there are no traps in database and it cannot find any host/ip address.
